# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Pull Request CI flow

on:
  pull_request:
    branches:
      - release/**
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B clean package -Pprod --file pom.xml

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Code coverage
        run: echo code coverage passed

  security:
    runs-on: ubuntu-latest
    steps:
      - name: Security check
        run: echo security check passed
